--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-server ."
      - "docker tag $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-server $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-server:latest"
  pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

version: 0.1

